### ISSUE TITLE
Problem using this Library with ESP8266 (nodemcu)

### ISSUE THREAD

**Issue by rafaeljohansen** [exscape/electronics#2]
Hey, thanks for making this library. When trying to use this with an ESP8266 I get errors about: 
'PORTB' was not declared in this scope.
I suppose this has something to do with things being defined differently in the ESP8266 compared to the Arduino. But I don't have the experience/understanding to fix this. Do you have any idea?

**Comment by exscape** [comment]
Is the ESP8266 compatible with Arduino libraries in general? I've never used one.  
If it does have Arduino functions such as digitalWrite, digitalRead, pinMode and so on, the library can probably be made to work quite easily, by removing the port write functionality. It won't be as fast, but unless you have fairly high speed requirements, that's not an issue.

If it does have the remaining Arduino compatibility, you can modify the library by removing all code that's run when `this->port_write` is true. For example, lines 136-138 would be deleted, and 139 left as-is. Same with 149-151, 167-169, 184-186 and 239-246 (plus the closing brace, of course).  
Doing so will remove all references to `PORTB` and `PORTD`, so the code may work then.

**Comment by exscape** [comment]
I came to think about this thread today as I was reading up using the ESP8266 myself, either as a full MCU (probably running Arduino code) or as just a Wi-Fi module addon.  
Because of that, I now have a bit of a better clue.

This library won't work with NodeMCU, because it has no source-level compatibility with Arduino.  
What you theoretically could do is to re-flash the ESP8266 to be Arduino-based, but that would make all your other code incompatible with it, instead.  
There's little to nothing I can do to help unfortunately; this library would have to be rewritten from scratch to work on NodeMCU.
